image: maven:3.8.6-jdk-11
stages:
  - .pre
  - pull
  - build 
  - remove-d
  - build-image
  - test
  - fuzz
  - sast
  - dast
  - performance
  - .post

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
 # - local: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/License-Scanning.gitlab-ci.yml
  # - template: Jobs/Build.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  # - template: Security/Coverage-Fuzzing.gitlab-ci.yml
  # - template: Security/DAST-API.gitlab-ci.yml
  # - template: Security/DAST-On-Demand-API-Scan.gitlab-ci.yml
  # - template: Security/DAST-On-Demand-Scan.gitlab-ci.yml
  - template: Security/DAST.gitlab-ci.yml

.pre:
  stage: .pre
  script: 
    - echo "pre stage"
  tags:
    - java_deploy

pull-code:
  stage: pull
  only:
  - main
  tags:
  - java_deploy
  script:
  - echo "preparing data and dependencies..."
  - pwd
  - ls

code_quality: 
  stage: test
  variables:
    CODE_QUALITY_IMAGE: "registry.gitlab.com/gitlab-org/ci-cd/codequality:latest"  
  allow_failure: true
  tags:
    - Docker_java_deploy

# fuzz:
#   stage: fuzz
#   script: 
#     - echo "fuzz stage"
#   tags:
#     - java_deploy

    
dast:
  tags:
    - java_deploy
  script:
    - echo "Test OK"  

SAST:
  tags:
    - java_deploy
  stage: test
  script:
    - echo "Test the job"  

build-code:
  stage: build
  only:
  - main
  tags:
  - java_deploy
  before_script:
  - echo "=======change permission ======="
  - chmod +x maveninstall.sh
  script:
  - echo "==== Project Building Started ====="
  - "./maveninstall.sh"
  - echo "code build Successfull..."
  - pwd
  when: on_success
  artifacts:
    paths:
    - target/*.war
    expire_in: 15 days

container_scanning:
  variables:
    GIT_STRATEGY: fetch
    DOCKERFILE_PATH: "$CI_PROJECT_DIR/Dockerfile"
    DOCKER_IMAGE: registry.gitlab.com/fineshift/java_deploy:latest
    SECURE_LOG_LEVEL: "debug"
  tags:
    - Docker_java_deploy


remove-old-docker:
  stage: remove-d
  only:
  - main
  tags:
  - java_deploy
  before_script:
  - echo "change permission of dockerrmf.sh"
  - chmod +x dockerrmf.sh
  script:
  - echo "Starting remove old docker image and container"
  - "./dockerrmf.sh"
  - echo "Removed all docker image and container"


build-docker-image:
  stage: build-image
  only:
  - main
  tags:
  - java_deploy
  needs:
  - build-code
  before_script:
  - chmod +x dockercmd.sh
  - echo "permission change"
  script:
  - "./dockercmd.sh"
  - echo "====Build And Deploy successfull.... ====="
