image: maven:3.8.6-jdk-11
stages:
  - .pre
  - pull
  - test
  - build 
  - remove-d
  - build-image
  - performance
  - .post

include:
 
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml 
  - template: Security/Container-Scanning.gitlab-ci.yml
#  - template: Security/DAST-On-Demand-API-Scan.gitlab-ci.yml
#  - template: Security/DAST-On-Demand-Scan.gitlab-ci.yml
#  - template: Security/DAST.gitlab-ci.yml





cache:
  paths:
    - data/


code_quality:
  stage: test
  tags:
    - maven-2

dependency_scanning:
  stage: test
  tags:
    - docker

sast:
  stage: test
  tags:
    - docker

license_scanning:
  stage: test
  tags:
    - docker



secret_detection:
  stage: test
  tags:
    - docker

.pre:
  stage: .pre
  script: 
    - sudo apt update -y
  tags:
    - maven-2
    
pull-code:
  stage: pull
  only:
  - main
  tags:
  - maven-2
  script:
  - echo "preparing data and dependencies..."
  - pwd
  - ls

build-code:
  stage: build
  only:
  - main
  tags:
  - maven-2
  before_script:
  - echo "=======change permission ======="
  - chmod +x maveninstall.sh
  script:
  - echo "==== Project Building Started ====="
  - "./maveninstall.sh"
  - echo "code build Successfull..."
  - pwd
  when: on_success
  artifacts:
    paths:
    - /.target/*.war
    expire_in: 15 days

remove-old-docker:
  stage: remove-d
  only:
  - main
  tags:
  - maven-2
  before_script:
  - echo "change permission of dockerrmf.sh"
  - chmod +x dockerrmf.sh
  script:
  - echo "Starting remove old docker image and container"
  - "./dockerrmf.sh"
  - echo "Removed all docker image and container"



build-docker-image:
  stage: build-image
  only:
  - main
  tags:
  - maven-2
  needs:
  - build-code
  before_script:
  - chmod +x dockercmd.sh
  script:
  - "./dockercmd.sh"
  - echo "====Build And Deploy successfull.... ====="


Container-scanning:
  stage: test
  script:
    - echo "container scanning is start"
  tags:
    - docker

# dast:
#   stage: dast
#   script: 
#     - echo "dast stage"
#   tags:
#     - maven-2

performance:
  stage: performance
  script: 
    - echo "performance stage"
  tags:
    - docker    
    
.post:
  stage: .post
  script: 
    - echo "post stage"
  tags:
    - docker   
    
