image: maven:3.8.6-jdk-11       #pull maven image
stages:
  - pull
  - build
  - remove-d
  - build-image


"pull-code":                       #Pull Stage
  stage: pull
  only:                         #script run only main branch 
    - main
  tags:                         #gitlab runner tag
    - maven-2
  script:
    - echo "preparing data and dependencies..."
    - pwd 
    - ls
  
"build-code":                 #Build Stage
  stage: build
  only:                     #script run only main branch 
    - main
  tags:                     #gitlab runner tag
    - maven-2
  before_script:
    - echo "=======change permission ======="
    - chmod +x maveninstall.sh                  #change permission of shell script file
  script:
    - echo "==== Project Building Started ====="
    - ./maveninstall.sh                     #execute shell file & build the code
    - echo "code build Successfull..."
    - pwd                               # present working directory 
  when: on_success          #after build successfull condition
  artifacts:                  # creating artifact
    paths:                      
      - target/*.war          #artifact path
    expire_in: 15 days         #expire artifact 
"remove-old-docker":
  stage: remove-d
  only:
    - main
  tags:
    - maven-2
  before_script:
    - echo "change permission of dockerrmf.sh"
    - chmod +x dockerrmf.sh
  script:
    - echo "Starting remove old docker image and container"
    - ./dockerrmf.sh
    - echo "Removed all docker image and container"
    
"build-docker-image":
  stage: build-image          # building docker image
  only:                         #execute only main branch
    - main
  tags:                          #gitlab runner tag
    - maven-2
  needs:                        #depends on build stage
    - build-code
  before_script:
    - chmod +x dockercmd.sh 
  script:
    - ./dockercmd.sh
    - echo "====Build And Deploy successfull.... ====="
