name: New Relic Monitor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  new_relic:
    name: New Relic Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Create monitors
        uses: arnaud-ritti/nr-monit@main
        with:
          config: "_monitors.yml" # (Required) Your configuration file, default : _monitors.yml
          api_key: a7c7061481254d5ab340df738d41a103FFFFNRAL
         
